# Generated by Django 5.1.4 on 2025-01-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='muallif',
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.muallif'),
            preserve_default=False,
        ),
    ]
